# Testing environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_test
    volumes:
      - ./api:/app
      - /app/var
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app_test}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      XDEBUG_MODE: "${XDEBUG_MODE:-coverage}"
    ports:
      - target: 80
        published: ${HTTP_PORT:-8001}
        protocol: tcp

  database:
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app_test}
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - db_data_test:/var/lib/postgresql/data

volumes:
  db_data_test:
