security:
  password_hashers:
    App\Entity\User: 'auto'
  enable_authenticator_manager: true
  providers:
    users:
      entity:
        class: App\Entity\User
        property: userIdentifier
  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
    main:
      stateless: true
      provider: users
      json_login:
        check_path: authentication
        username_path: userIdentifier
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~
  access_control:
   - { path: ^/$, roles: PUBLIC_ACCESS }    # Allows accessing Swagger UI
   - { path: ^/docs, roles: PUBLIC_ACCESS } # Allows accessing Swagger UI docs
   - { path: ^/authentication, roles: PUBLIC_ACCESS }
   - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
